version: '3.7'
services:
  db:
    image: postgres:16.2-alpine
    container_name: metrics-db
    volumes:
      - postgres:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=200'"
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - default
  api:
    build:
      context: ./metrics-backend
      dockerfile: Dockerfile
    container_name: metrics-api
    command: "./bin/rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - ./metrics-backend:/rails
      - bundle:/bundle
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    depends_on:
      - db

  frontend:
    build:
      context: ./metrics-frontend
      dockerfile: Dockerfile
    container_name: metrics-frontend
    command: sh -c "npm install && npm start"
    ports:
      - 4000:4000
    volumes:
      - ./metrics-frontend:/frontend
    depends_on:
      - api
networks:
  default:
    name: metrics

volumes:
  postgres:
  bundle:
