version: '3.7'
services:
  db:
    image: postgres:16.2-alpine
    container_name: metrics-db
    volumes:
      - postgres:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=200'"
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - default
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: metrics-web
    command: "./bin/rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
      - bundle:/bundle
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    env_file:
      - .env
    depends_on:
      - db
networks:
  default:
    name: metrics

volumes:
  postgres:
  web:
  bundle:
