# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'rack-cors'
gem 'rails', '~> 7.1.3'

gem 'tzinfo-data', platforms: %i[windows jruby]

gem 'bootsnap', require: false

group :development, :test do
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry', '~> 0.14.2'
  gem 'pry-byebug', '~> 3.10.1'
  gem 'pry-rails', '~> 0.3.9'
  gem 'rspec', '~> 3.13'
  gem 'rspec-rails', '~> 6.1'
end

group :development do
  gem 'annotate', '~> 3.2'
  gem 'rubocop', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'web-console', '>= 4.1.0'
end
